#!/usr/bin/env python3
"""Generate a read-only scene audit report for Godot scenes/scripts.

This script scans files under godot-port/scenes and writes a markdown report.
It does not modify any source scene or script files.
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
from pathlib import Path
from typing import Dict, List, Tuple


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_GODOT_ROOT = REPO_ROOT / "godot-port"


DEEP_DOLLAR_PATH_RE = re.compile(r"\$[A-Za-z_][A-Za-z0-9_]*/[A-Za-z0-9_./]+")
GET_NODE_PATH_RE = re.compile(r'get_node_or_null\("[^"\\]*?/[^"\\]*"\)')
RUNTIME_CONNECT_RE = re.compile(r"\.connect\(\"")
SCENE_CONNECTION_RE = re.compile(r"^\[connection signal=", re.MULTILINE)
FLATTENED_NODE_RE = re.compile(r'^\[node name="[^"]+@[^"]+"[^\n]*parent="\."\]', re.MULTILINE)


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def analyze_gd(path: Path) -> Dict[str, object]:
    text = read_text(path)
    deep_dollar_paths = len(DEEP_DOLLAR_PATH_RE.findall(text))
    get_node_paths = len(GET_NODE_PATH_RE.findall(text))
    runtime_connect_calls = len(RUNTIME_CONNECT_RE.findall(text))
    has_tool = bool(re.search(r"^tool\s*$", text, re.MULTILINE))
    uses_preview_sync = "EditorPreviewSync.sync_scene(" in text

    concerns: List[str] = []
    if deep_dollar_paths + get_node_paths >= 20:
        concerns.append("high node-path coupling")
    if runtime_connect_calls >= 6:
        concerns.append("many runtime signal connects")
    if has_tool and not uses_preview_sync:
        concerns.append("tool script missing EditorPreviewSync")

    return {
        "file": path,
        "kind": "gd",
        "deep_dollar_paths": deep_dollar_paths,
        "get_node_paths": get_node_paths,
        "runtime_connect_calls": runtime_connect_calls,
        "has_tool": has_tool,
        "uses_preview_sync": uses_preview_sync,
        "concerns": concerns,
    }


def analyze_tscn(path: Path) -> Dict[str, object]:
    text = read_text(path)
    scene_connections = len(SCENE_CONNECTION_RE.findall(text))
    flattened_nodes = len(FLATTENED_NODE_RE.findall(text))
    has_ui_scale_root = "[node name=\"UiScaleRoot\"" in text

    concerns: List[str] = []
    if flattened_nodes > 0:
        concerns.append("flattened node entries detected")

    return {
        "file": path,
        "kind": "tscn",
        "scene_connections": scene_connections,
        "flattened_nodes": flattened_nodes,
        "has_ui_scale_root": has_ui_scale_root,
        "concerns": concerns,
    }


def scan_scenes(root: Path) -> Tuple[List[Dict[str, object]], List[Dict[str, object]]]:
    gd_results: List[Dict[str, object]] = []
    tscn_results: List[Dict[str, object]] = []

    for path in sorted((root / "scenes").rglob("*.gd")):
        gd_results.append(analyze_gd(path))

    for path in sorted((root / "scenes").rglob("*.tscn")):
        tscn_results.append(analyze_tscn(path))

    return gd_results, tscn_results


def rel(path: Path, root: Path) -> str:
    return str(path.relative_to(root)).replace("\\", "/")


def render_report(root: Path, gd_results: List[Dict[str, object]], tscn_results: List[Dict[str, object]]) -> str:
    now = dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines: List[str] = []

    lines.append("# Scene Audit Auto Report")
    lines.append("")
    lines.append("Generated by tools/generate_scene_audit_report.py")
    lines.append("")
    lines.append(f"- Generated at: {now}")
    lines.append("- Scope: godot-port/scenes/**/*.gd and godot-port/scenes/**/*.tscn")
    lines.append("- Mode: read-only scan")
    lines.append("")

    total_flattened = sum(int(r["flattened_nodes"]) for r in tscn_results)
    total_runtime_connects = sum(int(r["runtime_connect_calls"]) for r in gd_results)
    total_scene_connects = sum(int(r["scene_connections"]) for r in tscn_results)

    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Script files scanned: {len(gd_results)}")
    lines.append(f"- Scene files scanned: {len(tscn_results)}")
    lines.append(f"- Runtime connect calls in scripts: {total_runtime_connects}")
    lines.append(f"- Scene-owned connections in tscn: {total_scene_connects}")
    lines.append(f"- Flattened node entries detected: {total_flattened}")
    lines.append("")

    lines.append("## Script Metrics")
    lines.append("")
    lines.append("| File | Deep $ paths | get_node_or_null paths | Runtime connect calls | Tool | Preview sync | Concerns |")
    lines.append("|------|--------------|------------------------|-----------------------|------|--------------|----------|")
    for r in gd_results:
        concerns = ", ".join(r["concerns"]) if r["concerns"] else "none"
        lines.append(
            "| {file} | {deep} | {gn} | {rc} | {tool} | {sync} | {concerns} |".format(
                file=rel(r["file"], root),
                deep=r["deep_dollar_paths"],
                gn=r["get_node_paths"],
                rc=r["runtime_connect_calls"],
                tool="yes" if r["has_tool"] else "no",
                sync="yes" if r["uses_preview_sync"] else "no",
                concerns=concerns,
            )
        )
    lines.append("")

    lines.append("## Scene Metrics")
    lines.append("")
    lines.append("| File | Scene connections | UiScaleRoot | Flattened nodes | Concerns |")
    lines.append("|------|-------------------|-------------|-----------------|----------|")
    for r in tscn_results:
        concerns = ", ".join(r["concerns"]) if r["concerns"] else "none"
        lines.append(
            "| {file} | {sc} | {scale} | {flat} | {concerns} |".format(
                file=rel(r["file"], root),
                sc=r["scene_connections"],
                scale="yes" if r["has_ui_scale_root"] else "no",
                flat=r["flattened_nodes"],
                concerns=concerns,
            )
        )
    lines.append("")

    lines.append("## Notes")
    lines.append("")
    lines.append("- This report is a heuristic snapshot; final categorization stays in SCENE_AUDIT_FINDINGS.md.")
    lines.append("- Flattened node entries with '@' are often signs of hierarchy drift that can break script paths.")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a read-only scene audit report")
    parser.add_argument(
        "--root",
        default=str(DEFAULT_GODOT_ROOT),
        help="Path to godot-port root (default: <repo>/godot-port)",
    )
    parser.add_argument(
        "--output",
        default="SCENE_AUDIT_AUTOGEN.md",
        help="Output markdown path, relative to --root",
    )
    args = parser.parse_args()

    root = Path(args.root).resolve()
    output = root / args.output

    gd_results, tscn_results = scan_scenes(root)
    report = render_report(root, gd_results, tscn_results)

    output.write_text(report + "\n", encoding="utf-8")
    print(f"Wrote report: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
